applications/bonita-user-application.xml
pom.xml

[Covers BPO-213](https://bonitasoft.atlassian.net/browse/BPO-213)

feat (case list) integrate case list

---

infrastructure/buildVersion.groovy
infrastructure/upload-github-release-asset.sh

feat(release) upload release asset when building tag

---

applications/bonita-user-application.xml

Covers [BPO-404](https://bonitasoft.atlassian.net/browse/BPO-404)
After [#229](https://github.com/bonitasoft/bonita-web-pages/pull/229) has been merged, the layout version should be changed  to V5, so I suggest modifying and merging this one after [#229](https://github.com/bonitasoft/bonita-web-pages/pull/229).

feat(user application) Update user application version

---

applications/bonita-user-application.xml

Covers no tickets
Relates to [#316](https://github.com/bonitasoft/bonita-web-pages/pull/316)

Update details token to be consistent with other lists

---

applications/bonita-user-application.xml

covers [BPO-507](https://bonitasoft.atlassian.net/browse/BPO-507)

feat(user app) Make app links consistent

---

applications/bonita-user-application.xml

- this new version includes the case details page and an update of the layout version

version update for 7.11

---

applications/bonita-user-application.xml

- a pagination issue was fixed in the user case list leading to a version update of the page
Covers [BPO-622](https://bonitasoft.atlassian.net/browse/BPO-622)

fix (user case list) use latest version of the page

---

applications/bonita-user-application.xml
pom.xml

should be merged with bonitasoft/bonita-web-pages/pull/405

feat(layout) use latest version of the layout

---

applications/bonita-user-application.xml
pom.xml

Is connected to [#480](https://github.com/bonitasoft/bonita-web-pages/pull/480)
Covers [BR-635](https://bonitasoft.atlassian.net/browse/BR-635)

fix (layout): Change layout version

---

pom.xml

this is a artifact in itself, also declare dependencies on the pages in order to let consumers of that artifact be able to retrieve all pages required
Relates to [RUNTIME-183](https://bonitasoft.atlassian.net/browse/RUNTIME-183)

feat: publish xml of the application

---

pom.xml
zip-with-resources-assembly.xml

* add new zip with resources package including the built version of the application pages
* only bundle the non provided pages
Covers [RUNTIME-263](https://bonitasoft.atlassian.net/browse/RUNTIME-263)

 feat(packaging): add new zip with resources package

---

bonita-distrib/bonita-user-application.xml

* add Bonita suffix like for pages tokens

feat(app token): update app token so that there may not be any conflict with an existing app while migrating

---

.gitignore
applications/bonita-user-application.xml
bonita-distrib/bonita-user-application.xml

Relates to [RUNTIME-366](https://bonitasoft.atlassian.net/browse/RUNTIME-366)

feat: add description to the application

---

infrastructure/change_version.sh

exclude bos-distrib folder when changing the release version

fix(release): update change version script

---

bonita-distrib/bonita-user-application.xml

covers [RUNTIME-380](https://bonitasoft.atlassian.net/browse/RUNTIME-380)

fix(user app): Fix user case list page token for distrib

---

bonita-distrib/bonita-user-application.xml

Reverts bonitasoft/bonita-user-application#28

Revert "fix(user app): Fix user case list page token for distrib"

---

bos-distrib/applications/bonita-user-application.xml

covers [RUNTIME-472](https://bonitasoft.atlassian.net/browse/RUNTIME-472)
relates to [#111](https://github.com/bonitasoft/bonita-web-pages-internal/pull/111)

chore(layout): Update Bonita layout version

---

bos-distrib/applications/bonita-user-application.xml
pom.xml

Covers [RUNTIME-1301](https://bonitasoft.atlassian.net/browse/RUNTIME-1301)

Feat (Bonita User Application): Update application page version

---

bos-distrib/applications/bonita-user-application.xml

covers [RUNTIME-1335](https://bonitasoft.atlassian.net/browse/RUNTIME-1335)
related to [#59](https://github.com/bonitasoft/bonita-web-pages-sp/pull/59)

chore(layout): Update layout version

---

bos-distrib/applications/bonita-user-application.xml
pom.xml

Covers [RUNTIME-1528](https://bonitasoft.atlassian.net/browse/RUNTIME-1528)

Feat (Bonita User Application): Upgrade user case list page version

---

bos-distrib/applications/bonita-user-application.xml
pom.xml

Covers [DEV-220](https://bonitasoft.atlassian.net/browse/DEV-220)
Depends on bonitasoft/bonita-web-pages-sp/pull/218
[DEV-220]: https://bonitasoft.atlassian.net/browse/DEV-220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(update pages versions): follow bonita-web-pages updates

---

bos-distrib/applications/bonita-user-application.xml

covers [RUNTIME-1364](https://bonitasoft.atlassian.net/browse/RUNTIME-1364)
relates to [#256](https://github.com/bonitasoft/bonita-web-pages-sp/pull/256)
[RUNTIME-1364]: https://bonitasoft.atlassian.net/browse/RUNTIME-1364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(pages): update page versions

---

pom.xml
src/main/resources/bos-distrib/applications/bonita-user-application.xml

Covers [DEV-524](https://bonitasoft.atlassian.net/browse/DEV-524)
Depends on https://github.com/bonitasoft/bonita-web-pages-sp/pull/290
[DEV-524]: https://bonitasoft.atlassian.net/browse/DEV-524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

 feat(maintenance mode): update layout version and app version

---

bos-distrib/applications/bonita-user-application.xml

Covers [RUNTIME-1806](https://bonitasoft.atlassian.net/browse/RUNTIME-1806)
[RUNTIME-1806]: https://bonitasoft.atlassian.net/browse/RUNTIME-1806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat (bonita user application): update page versions

---

bos-distrib/applications/bonita-user-application.xml

Covers [RUNTIME-1806](https://bonitasoft.atlassian.net/browse/RUNTIME-1806)
[RUNTIME-1806]: https://bonitasoft.atlassian.net/browse/RUNTIME-1806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat (user application): update application page version

---

bos-distrib/applications/bonita-user-application.xml

Covers [RUNTIME-1806](https://bonitasoft.atlassian.net/browse/RUNTIME-1806)
[RUNTIME-1806]: https://bonitasoft.atlassian.net/browse/RUNTIME-1806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat (bonita user application): update page version

---

src/main/resources/bonita-distrib/bonita-user-application.xml
src/main/resources/bos-distrib/applications/bonita-user-application.xml

Related to [BPM-110](https://bonitasoft.atlassian.net/browse/BPM-110)
[BPM-110]: https://bonitasoft.atlassian.net/browse/BPM-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(xmlns): bump application-xml-schema from 1.0 to 1.1

---

pom.xml
src/main/resources/bos-distrib/applications/bonita-user-application.xml

Related to [BPM-114](https://bonitasoft.atlassian.net/browse/BPM-114)
[BPM-114]: https://bonitasoft.atlassian.net/browse/BPM-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(layout): upgrade layout version

---

bos-distrib/applications/bonita-user-application.xml
pom.xml

Covers [RUNTIME-1889](https://bonitasoft.atlassian.net/browse/RUNTIME-1889)
[RUNTIME-1889]: https://bonitasoft.atlassian.net/browse/RUNTIME-1889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat (layout): update layout version
